rm -rf BAM/
rm -rf benchmark/
rm -rf BWA/
rm -rf finalReport*
rm -rf MockReference/
rm -rf MPILEUP/
rm -rf QC/
rm -rf SAM/
rm -rf FASTQ/CONCATENATED/
rm -rf FASTQ/TRIMMED/
rm -rf VCF/
rm -rf .snakemake/
