__default__:
    time: 00:30:00
    job-name:  GBSDefault
    account: project_2001746
    ntasks: 1
    cpus-per-task: 1
    mem-per-cpu: 4000
    partition: small
    working-directory: /scratch/project_2001746/logs/
    nvme: 0
    mail-user: daniel.fischer@luke.fi
    mail-type: FAIL

# Module 0 - PreparationsAndIndexing:
################################################################################

star_create_index:
    job-name:  Create-StarIndex
    time: 05:00:00
    cpus-per-task: 20
    mem-per-cpu: 4000

Concatenate_lanes:
    job-name: Concatenate_lanes
    time: 01:00:00
    cpus-per-task: 1
    mem-per-cpu: 4000

bwa_create_index:
    job-name:  Create-bwaIndex
    time: 05:00:00
    cpus-per-task: 1
    mem-per-cpu: 50000

bwa_create_insilico_index:
    job-name: bwa_create_insilico_index
    time: 05:00:00
    cpus-per-task: 1
    mem-per-cpu: 50000
    
IndexMockReferenceBWA:
    job-name:  IndexMockRefGenome_BWA
    time: 02:00:00
    cpus-per-task: 1
    mem-per-cpu: 25000
    
IndexMockReferenceSamtools:
    job-name:  IndexMockRefGenome_Samtools
    time: 02:00:00
    cpus-per-task: 1
    mem-per-cpu: 25000

IndexClustersBWA:
    job-name:  IndexMockRefClusters_BWA
    time: 02:00:00
    cpus-per-task: 1
    mem-per-cpu: 25000

IndexClustersSamtools:
    job-name:  IndexMockRefClusters_Samtools
    time: 02:00:00
    cpus-per-task: 1
    mem-per-cpu: 25000

IndexFinalMockBWA:
    job-name:  IndexFinalMockBWA
    time: 02:00:00
    cpus-per-task: 1
    mem-per-cpu: 25000

IndexFinalMockSamtools:
    job-name:  IndexFinalMockSamtools
    time: 02:00:00
    cpus-per-task: 1
    mem-per-cpu: 25000

R_createBarcodesID_file:
    job-name: R_createBarcodesID_file
    time: 00:00:10
    cpus-per-task: 1
    mem-per-cpu: 4000

# Module 1 - QC:
################################################################################
fastqc_quality_control_raw_data_r1:
    time: 05:00:00
    job-name: fastqc-raw
    cpus-per-task: 20
    mem-per-cpu: 4000
    
multiqc_quality_control_raw_data_r1:
    time: 05:00:00
    job-name: multiqc-raw
    mem-per-cpu: 32000
    cpus-per-task: 1
    nvme: 10

qualDist_raw_data:
    job-name: qualDist-raw
    
fastqc_quality_control_concatenated_data:
    time: 05:00:00
    job-name: fastqc-conc
    cpus-per-task: 20

multiqc_quality_control_concatenated_data:
    time: 05:00:00
    job-name: multiqc-conc
    mem-per-cpu: 32000
    nvme: 10

qualDist_concateated_data:
    job-name: qualDist-conc

fastqc_quality_control_trimmed_data:
    time: 05:00:00
    job-name: fastqc-trimmed
    cpus-per-task: 20

multiqc_quality_control_trimmed_data:
    time: 05:00:00
    job-name: multiqc-trimmed
    mem-per-cpu: 32000
    nvme: 10    

qualDist_trimmed_data:
   job-name: qualDist-trimmed
   
# Module 2 - DataPreprocessing
################################################################################
cutadapt_trim_reads:
    time: 02:00:00
    job-name:  AdapterTrimming

TrimBasedOnQuality:
    time: 04:00:00
    job-name:  QualityTrimming
    cpus-per-task: 20
    mem-per-cpu: 2000

SubstituteLowQualityBases:
    time: 04:00:00
    job-name:  SubstituteLowQualityBases
    mem-per-cpu: 8000

# Module 3 - MockReference   
################################################################################   
CreateClusterAndMockReference:
    time: 1-00:00:00
    job-name:  CreateClusterAndMockReference
    cpus-per-task: 20
    mem-per-cpu: 4000
    nvme: 500

MockVsRef_alignment:
    time: 05:00:00
    cpus-per-task: 20
    job-name:  MockVsRef_alignment

MockVsRef_samtools_SamToSortedBam:
    time: 05:00:00
    job-name:  MockVsRef_samtools_SamToSortedBam

MockVsRef_AlignmentStats:
    time: 05:00:00
    job-name: MockVsRef_AlignmentStats

FinalMockVsRef_alignment:
    time: 05:00:00
    cpus-per-task: 20
    job-name:  FinalMockVsRef_alignment

FinalMockVsRef_samtools_SamToSortedBam:
    time: 05:00:00
    job-name:  FinalMockVsRef_samtools_SamToSortedBam

FinalMockVsRef_AlignmentStats:
    time: 05:00:00
    job-name: FinalMockVsRef_AlignmentStats

MockVsRef_SortedBamToMpileup:
    time: 05:00:00
    job-name: MockVsRef_SortedBamToMpileup

refine_mock_reference:
    time: 05:00:00
    job-name: refine_mock_reference
    mem-per-cpu: 64000

Mockrefloci_vs_samplealignments:
    time: 05:00:00
    job-name: Mockrefloci_vs_samplealignments

MockInRef_similarity:
    time: 05:00:00
    job-name: MockInRef_similarity
    mem-per-cpu: 150000

MockVsInsilico_alignment:
    time: 05:00:00
    cpus-per-task: 20
    job-name:  MockVsInsilico_alignment

MockVsInsilico_samtools_SamToSortedBam:
    time: 05:00:00
    job-name:  MockVsInsilico_samtools_SamToSortedBam

MockVsInsilico_AlignmentStats:
    time: 05:00:00
    job-name: MockVsInsilico_AlignmentStats

# Module 4 - Read alignment
################################################################################   
RefGenome_AlignReads:
    time: 05:00:00
    job-name:  AlignReadsToReference
    cpus-per-task: 20
    mem-per-cpu: 15000

RefGenome_SamToSortedBam:
    time: 05:00:00
    job-name:  SamToSortedBamReference
    mem-per-cpu: 30000

RefGenome_SortedBamToMpileup:
    time: 05:00:00
    job-name:  SortedBamToMpileupReference
    mem-per-cpu: 30000

RefGenome_AlignmentStats:
    time: 05:00:00
    job-name:  RefGenome_AlignmentStats
    cpus-per-task: 1
    mem-per-cpu: 30000

MockRef_AlignReads:
    time: 01:00:00
    job-name:  MockRef_AlignReads
    cpus-per-task: 20
    mem-per-cpu: 5000

MockRefClusters_AlignReads:
    time: 01:00:00
    job-name:  MockRefClusters_AlignReads
    cpus-per-task: 20
    mem-per-cpu: 5000

MockRef_SamToSortedBam:
    time: 01:00:00
    job-name:  MockRef_SamToSortedBam
    cpus-per-task: 20
    mem-per-cpu: 5000

MockRefClusters_SamToSortedBam:
    time: 01:00:00
    job-name:  MockRefClusters_SamToSortedBam
    cpus-per-task: 20
    mem-per-cpu: 5000

MockRef_SortedBamToMpileup:
    time: 01:00:00
    job-name:  MockRef_SortedBamToMpileup
    cpus-per-task: 20
    mem-per-cpu: 5000

MockRef_AlignmentStats:
    time: 01:00:00
    job-name:  MockRef_AlignmentStats
    cpus-per-task: 20
    mem-per-cpu: 5000

MockRefClusters_AlignmentStats:
    time: 01:00:00
    job-name:  MockRefClusters_AlignmentStats
    cpus-per-task: 20
    mem-per-cpu: 5000

FinalMockRef_AlignReads:
    time: 01:00:00
    job-name:  FinalMockRef_AlignReads
    cpus-per-task: 20
    mem-per-cpu: 5000
  
FinalMockRef_SamToSortedBam:
    time: 01:00:00
    job-name: FinalMockRef_SamToSortedBam
    cpus-per-task: 20
    mem-per-cpu: 5000

FinalMockRef_SortedBamToMpileup:
    time: 01:00:00
    job-name:  FinalMockRef_SortedBamToMpileup
    cpus-per-task: 20
    mem-per-cpu: 5000

finalMockRef_AlignmentStats:
    time: 01:00:00
    job-name:  FinalMockRef_AlignmentStats
    cpus-per-task: 20
    mem-per-cpu: 5000

# Module 5 - Call Variants
################################################################################   

ParseMpileup_createCountFiles:
    time: 05:00:00
    job-name:  createCountFiles_mockref
    mem-per-cpu: 16000

ParseMpileup_createCountFiles_finalMock:
    time: 05:00:00
    job-name:  createCountFiles_finalmock
    mem-per-cpu: 16000

ParseMpileup_createCountFiles_reference:
    time: 05:00:00
    job-name:  createCountFiles_reference
    mem-per-cpu: 16000

create_verticalRef:
    time: 05:00:00
    job-name:  create_verticalRef
    mem-per-cpu: 32000
    nvme: 50

create_verticalRef_finalMock:
    time: 05:00:00
    job-name:  create_verticalRef_finalMock
    mem-per-cpu: 32000
    nvme: 50

create_verticalRef_reference:
    time: 05:00:00
    job-name:  create_verticalRef_reference
    mem-per-cpu: 32000
    nvme: 50

cut_verticalRef:
    job-name: cut_verticalRef
    
cut_verticalRef_reference:
    job-name: cut_verticalRef_reference

cut_verticalRef_finalMock:
    job-name: cut_verticalRef_finalMock

create_MasterMatrix_parallel:
    time: 1-00:00:00
    job-name:  create_MasterMatrix_parallel
    mem-per-cpu: 128000

create_MasterMatrix_parallel_finalMock:
    time: 1-00:00:00
    job-name:  create_MasterMatrix_parallel_finalMock
    mem-per-cpu: 128000

create_MasterMatrix_parallel_reference:
    time: 1-00:00:00
    job-name:  create_MasterMatrix_parallel_reference
    mem-per-cpu: 128000

aggregate_MasterMatrix:
    job-name: aggregate_MasterMatrix
    time: 0-12:00:00
    mem-per-cpu: 84000

aggregate_MasterMatrix_finalMock:
    job-name: aggregate_MasterMatrix_finalMock
    time: 0-12:00:00
    mem-per-cpu: 84000
    
aggregate_MasterMatrix_reference:
    job-name: aggregate_MasterMatrix_reference
    time: 0-12:00:00
    mem-per-cpu: 84000
    
FilterVariants:
    time: 1-12:00:00
    job-name:  filterVariants
    mem-per-cpu: 30000

FilterVariants_reference:
    time: 1-12:00:00
    job-name:  filterVariants_reference
    mem-per-cpu: 30000
    
FilterVariants_finalMock:
    time: 1-12:00:00
    job-name:  filterVariants_finalMock
    mem-per-cpu: 30000
 
CreateVCF:
    time: 01:00:00
    job-name: CreateVCF
    mem-per-cpu: 30000    

CreateVCF_reference:
    time: 01:00:00
    job-name:  CreateVCF_reference
    mem-per-cpu: 30000

CreateVCF_finalMock:
    time: 01:00:00
    job-name:  CreateVCF_finalMock
    mem-per-cpu: 30000

# Module 6 - Postprocessing
################################################################################
Ref_getVariantFlanking:
    time: 02:00:00
    job-name:  Ref_getVariantFlanking
    
MockRef_getVariantFlanking:
    time: 05:00:00
    job-name:  MockRef_getVariantFlanking

AlignMockFlankingToReference:
    job-name:  AlignMockFlankingToReference
    cpus-per-task: 20
    mem-per-cpu: 5000

MockFlankingToReference_SamToSortedBam:
    job-name: MockFlankingToReference_SamToSortedBam
    cpus-per-task: 20
    mem-per-cpu: 1000

# Module 7 - Reporting
################################################################################
R_finalReport:
    time: 0-12:00:00
    job-name: Finalreport
    mem-per-cpu: 80000
    
R_QCReport:
    time: 0-06:00:00
    job-name: QCreport
    mem-per-cpu: 80000

R_VariantCallingReport:
    time: 0-03:00:00
    job-name: VariantCallingreport
    mem-per-cpu: 80000

R_InsilicoReport:
    time: 0-03:00:00
    job-name: InsilicoReport
    mem-per-cpu: 32000


# Module 8 - Call new data
################################################################################
ExistingMockRefGenome_AlignReads:
    job-name: ExistingMockRefGenome_AlignReads
    time: 01:00:00
    cpus-per-task: 20
    mem-per-cpu: 5000

ExistingMockRefGenome_SamToSortedBam:
    job-name: ExistingMockRefGenome_SamToSortedBam
    time: 01:00:00
    cpus-per-task: 20
    mem-per-cpu: 5000

ExistingMockRefGenome_SortedBamToMpileup:
    job-name: ExistingMockRefGenome_SortedBamToMpileup
    time: 01:00:00
    cpus-per-task: 20
    mem-per-cpu: 5000

ExistingMockRefGenome_mergeVCFs:
    job-name: ExistingMockRefGenome_mergeVCFs
    time: 01:00:00
    cpus-per-task: 5
    mem-per-cpu: 50000
    
ExistingMockRefGenome_AlignmentStats:
    job-name: ExistingMockRefGenome_AlignmentStats
    time: 01:00:00
    cpus-per-task: 20
    mem-per-cpu: 5000

ParseMpileup_createCountFiles_existingMockreference:
    job-name: ParseMpileup_createCountFiles_existingMockreference
    time: 05:00:00
    mem-per-cpu: 16000

create_verticalRef_existingMockreference:
    job-name: create_verticalRef_existingMockreference
    time: 01:00:00
    mem-per-cpu: 16000
    nvme: 20
    
create_MasterMatrix_parallel_existingMockreference:
    job-name: create_MasterMatrix_parallel_existingMockreference
    time: 0-12:00:00
    mem-per-cpu: 64000
    nvme: 20

aggregate_MasterMatrix_existingMockreference:
    job-name: aggregate_MasterMatrix_existingMockreference
    time: 0-12:00:00
    mem-per-cpu: 48000
    nvme: 20

FilterVariants_existingMockreference:
    job-name: FilterVariants_existingMockreference
    time: 1-12:00:00
    mem-per-cpu: 30000

CreateVCF_existingMockreference:
    job-name: CreateVCF_existingMockreference
    time: 01:00:00
    mem-per-cpu: 30000

# Module 9:
###############################################################################
featureCounts_quantify_ReferenceAlignments:
    job-name: featureCounts_quantify_ReferenceAlignments
    time: 01:00:00
    mem-per-cpu: 30000
    
prepare_liftOverchain_minimap2:
    job-name: prepare_liftOverchain_minimap2
    time: 05:00:00
    cpus-per-task: 20

convertVCF_transanno:
    job-name: convertVCF_transanno
    time: 05:00:00
    cpus-per-task: 20
    
# Module 10:
###############################################################################
R_createInSilicoFasta:
    job-name:  R_createInSilicoFasta
    time: 01:00:00
    mem-per-cpu: 30000
    
InsilicoGenome_AlignReads:
    job-name: InsilicoGenome_AlignReads
    time: 05:00:00
    cpus-per-task: 20
    mem-per-cpu: 15000   
    
InsilicoGenome_SamToSortedBam:
    job-name: InsilicoGenome_SamToSortedBam
    time: 05:00:00
    mem-per-cpu: 30000
    
Insilico_AlignmentStats:
    job-name: Insilico_AlignmentStats
    time: 05:00:00
    cpus-per-task: 1
    mem-per-cpu: 30000
